### ISSUE TITLE
Feature request: "due date" for new issue

### ISSUE THREAD

**Issue by matsbrucke** [wolfgangimig/itol#10]
Hi,

Could you add a field "due date" when generating a new issue?

best

Matthias
PS: I presented your plugin to my colleagues yesterday and they all liked (so there will be additional users in the near future ;)

**Comment by Sledav** [comment]
Hi,
In our company realized if the field "due date" is empty, then the value is automatically set Today+5 days.
For us, it would be wonderful to add the ability to specify custom field. Because we have the required custom fields

**Comment by wolfgangimig** [comment]
Thank you for your proposals. It's nice to here that people find the addin useful.
Since the space in the UI is limited, I think about having a "Details" dialog that presents additional options in a table.

**Comment by matsbrucke** [comment]
Hi,

It could also be a field in the options setting, which is fixed for all issues (and it could really be "tomorrow" or "today + 5"). We handle it in a way the the person responsible for the tickets looks into the ticket, changes the status to "I work on it", calculates the amount of time it will take and sets the due date.

By having it due "tomorrow" I force them to look at it soon ;)

**Comment by matsbrucke** [comment]
btw: there could also be default settings for other fields like "responsible person". "Project", etc.

May I still ask for the "New issue" button in the list view of outlook, it saves my a double click ;)

have a nice weekend

**Comment by wolfgangimig** [comment]
Currently, I'm working on integrating the issue dialog with the explorer window (the main Outlook window). I plan to add a toolbar to the issue dialog where you can choose "...from mail..." or "...blank..." (don't know how to name the buttons right now). The "...blank..." button belongs to the "New issue" functionality, you are requesting. 
The advantage of having the "New issue" dialog integrated in the main window over a modal dialog is, that you can still access the Outlook UI while editing the issue properties. A non-modal dialog would switch into the background, if you click some function in Outlook.

**Comment by matsbrucke** [comment]
sounds good ;)
