### ISSUE TITLE
Field problem

### ISSUE THREAD

**Issue by balagab** [wolfgangimig/itol#13]
Hello,

When trying to add issue I get the fields in a really strange format:
![kepkivagas](https://cloud.githubusercontent.com/assets/7058332/6105306/fcb7654a-b055-11e4-887d-7ff75d8aefa9.JPG)

If I click to the arrow, or the "..." does happen nothing. I can't choose any value.
We are using MS SQL db.

Thanks,
Gabor

**Comment by wolfgangimig** [comment]
This happens, when an internal error occurs while reading configurations from redmine. Please enable logging as described [here](https://github.com/wolfgangimig/itol/wiki/Enable-Logging).

**Comment by balagab** [comment]
Ok thanks I will check with other redmine server it's ok, so it's something with my redmine server.
This is a great plugin, is it possible to implement this feature into new mail in outlook? I mean now I can create issue only from a mail from inbox, but it would be great if I could create from new mail.

Thanks

**Comment by wolfgangimig** [comment]
Thank your for being interested. I' m working on integrating the issue dialog into the Outlook explorer window (the main window). This will allow to create a new blank issue without a mail in background.

**Comment by balagab** [comment]
it would be great, thank you for yor professional work!
