### ISSUE TITLE
Description editor colours

### ISSUE THREAD

**Issue by dan-sorion** [wolfgangimig/itol#18]
The description editor shows up with what appears to be a random mix of pink, green, and grey buttons and text editor area. Hovering over buttons, clicking buttons, and hovering/clicking/typing in the text editor area appears to switch these around at random causing the interface to be a flickering combination of colours which is very distracting.

I've checked the CSS that the IssueServiceImpl.js is retrieving from Redmine and it doesn't contain these colours, so it looks like the CSS isn't at fault here. Is there any way to customise these colours, or at the very least have them not flicker from one colour to another while typing/moving the mouse. It would be great if the colours would match the jstoolbar.css colours and the appropriate text area CSS, or even just have a plain white description editor box and simple grey buttons just like the default Redmine editor.

I'm using Outlook 2013 32-bit on Windows 7 Pro SP1, in case the version of OL or Win is partly responsible for this.

Dan

**Comment by wolfgangimig** [comment]
In my experience, this problem is caused by the DEBUG log level. Check ITOL configuration and change to INFO. 
Regards
Wolfgang

**Comment by dan-sorion** [comment]
Hi Wolfgang,

Thanks, that's fixed it. Are you using the odd colour cycling as part of the debugging to test for events firing?

Dan

**Comment by wolfgangimig** [comment]
Hi Dan,
This play of colors is not made by me. It happens deep inside the JavaFX web component. Maybe you're right, that the developers try to make events visible.
Regards
Wolfgang

**Comment by dan-sorion** [comment]
Hi Wolfgang,

Thanks for looking into this, I'll close it now as a non-issue.

Regards,

Dan
