### ISSUE TITLE
Fields in properties tab do not change when project changes

### ISSUE THREAD

**Issue by cpekyaman** [wolfgangimig/itol#21]
We recently started using this plugin and it is really very useful. 

We have two projects in redmine and they have different sets of fields. It looks like properties tab shows fields from both projects and also I can't see which fields are required. It may not be very vital to see role dependent required information but It would be nice to see only fields for the selected project and see which fields are required by default.

Is this expected behavior or do we need to make some more configuration ?

Thanks.

**Comment by wolfgangimig** [comment]
Unfortunately, the Redmine API does not provide the project-to-field relation, see http://www.redmine.org/issues/16523

As a workaround, you can add the relation in the JavaScript code of ITOL. Go though the following steps:
- Exit Outlook
- ensure you got ITOL version 1.3 installed.
- open file c:\users\username\AppData\Local\Issue Tracker...\app\IssueServiceImpl.js in a text editor (e.g. notepad)
- lookup line 
  
  ```
  function isCustomFieldForIssueType(cfield, issue) {
  ```
- insert the following code block before that line. Modify as described at TODO.
  
  ```
  // TODO: Names of fields used in all projects:
  // Add one line for each field in format ... "fieldname" : true,
  var customFieldsInAllProjects = {
          "Workflow ID" : true, // example
          "Cost Center" : true, // example
  };
  
  // TODO: Field to project relationship.
  // Add one line for each relation in format ... "fieldname in projectname" : true,
  var mapCustomFieldsToProjects = {
          "Notify docu in OutlDD" : true, // example
  };
  
  function isCustomFieldForProject(cfield, issue) {
      var ret = customFieldsInAllProjects[cfield.name];
      if (!ret) {
          var project = getIssueProject(issue);
          if (project) {
              ret = mapCustomFieldsToProjects[cfield.name + " in " + project.name];
          }
      }
      return ret;
  }
  ```
- lookup lines 
  
  ```
      var cfield = data.custom_fields[i];
      if (isCustomFieldForIssueType(cfield, issue)) {
  ```
- modify as follows:
  
  ```
      var cfield = data.custom_fields[i];
      if (!isCustomFieldForProject(cfield, issue)) continue;
      if (isCustomFieldForIssueType(cfield, issue)) {
  ```
- Save IssueServiceImpl.js
- Start Outlook

**Comment by cpekyaman** [comment]
thanks for your tip. It seems easy enough to apply without any problems. I'll try it, if this problem begins to cause usability issues for our redmine users. 

thanks again.
