### ISSUE TITLE
Project without issue tracking module

### ISSUE THREAD

**Issue by sgissinger** [wolfgangimig/itol#22]
Projects which do not have issue tracking module enabled appear in the projects combobox.
And as a side effect, the plugin tries to retrieve categories from these projects and REST returns a 403 error.

**Comment by wolfgangimig** [comment]
- Make sure you have installed the latest version 1.3. 
- Set logging level DEBUG in configuration, click Save button
- From the log file, post the lines between 
  
  ```
  ... getProjectIdNames(
  ...
  ... )getProjectIdNames
  ```

**Comment by sgissinger** [comment]
Ok, we made a RedMine update from 2.5.2 to 2.6 and now it works fine.
Sorry I read Itol requirements a little too fast.
