### ISSUE TITLE
SSL certificate errors

### ISSUE THREAD

**Issue by sgissinger** [wolfgangimig/itol#23]
With a self signed certificate or a MS Exchange SSL certificate, SSL handshake failed.
Could it be possible to add checkbox in the plugin configuration to **Ignore SSL certificate errors** ?

Maybe with a warning to inform users that this should only be checked in a safe and controlled environnement. If the user do not know what it means, he must leave it unchecked.

**Comment by wolfgangimig** [comment]
Please follow [this steps](https://github.com/wolfgangimig/itol/wiki/How-to-import-HTTPS-certificate) in order to import a self signed certificate into the JVM of ITOL.

**Comment by sgissinger** [comment]
Ok, but it complicates deployment a little.
