### ISSUE TITLE
Configuration Error if redmine is using https://

### ISSUE THREAD

**Issue by jackfly151** [wolfgangimig/itol#27]
When configuring issue tracker with redmine under https i have the following error

![redmine error https](https://cloud.githubusercontent.com/assets/13963911/9468221/bb475b98-4b40-11e5-84c3-ed92457a11be.jpg)

Any idea ?
thanks for your help?

**Comment by wolfgangimig** [comment]
Please make sure, that the certificate used for the server was created for the host name given in your URL.

**Comment by jackfly151** [comment]
Yes it is !  
but the certificate is given by  our  own private CA ; 
I tried to add the CA certificate in the approuved CA certificate list  in JAVA config  . Always the same error.

thanks for your help.. one more time

**Comment by wolfgangimig** [comment]
Have you tried this steps:
https://github.com/wolfgangimig/itol/wiki/How-to-import-HTTPS-certificate

?
