### ISSUE TITLE
can't connect to redmine

### ISSUE THREAD

**Issue by ghost** [wolfgangimig/itol#29]
Hello.
I'm using redmine on my company's server. We're using SSL and self-signed sertificate. 
Logs tell me this:

> 2015-09-14 18:13:03,382 FINE com.wilutions.joa.fx.ModalDialogFX internalShowAsync )internalShowAsync
> 2015-09-14 18:13:03,382 FINE com.wilutions.joa.fx.ModalDialogFX internalShowAsync internalShowAsync([Explorer[Dispatch 1be7df50]]
> 2015-09-14 18:13:03,383 FINE com.wilutions.joa.fx.ModalDialogFX internalShowAsync createScene
> 2015-09-14 18:13:03,392 FINE com.wilutions.joa.fx.ModalDialogFX internalShowAsync create joaDlg...
> 2015-09-14 18:13:13,396 SEVE com.wilutions.joa.fx.ModalDialogFX internalShowAsync Failed to show dialog
> com.wilutions.com.ComException Cannot find JoaUtilAddin.
>     at com.wilutions.joa.OfficeAddin.getJoaUtil(OfficeAddin.java:195)
>     at com.wilutions.joa.fx.ModalDialogFX.internalShowAsync(ModalDialogFX.java:397)
>     at com.wilutions.joa.fx.ModalDialogFX.lambda$0(ModalDialogFX.java:139)
>     at com.wilutions.joa.fx.ModalDialogFX$$Lambda$92/2058867551.run(Unknown Source)
>     at com.sun.javafx.application.PlatformImpl.lambda$null$170(PlatformImpl.java:295)
>     at com.sun.javafx.application.PlatformImpl$$Lambda$51/488541779.run(Unknown Source)
>     at java.security.AccessController.doPrivileged(Native Method)
>     at com.sun.javafx.application.PlatformImpl.lambda$runLater$171(PlatformImpl.java:294)
>     at com.sun.javafx.application.PlatformImpl$$Lambda$50/107973214.run(Unknown Source)
>     at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
>     at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
>     at com.sun.glass.ui.win.WinApplication.lambda$null$145(WinApplication.java:101)
>     at com.sun.glass.ui.win.WinApplication$$Lambda$39/2138102412.run(Unknown Source)
>     at java.lang.Thread.run(Thread.java:745)
> 
> 2015-09-14 18:13:13,396 FINE com.wilutions.joa.fx.ModalDialogFX internalShowAsync )internalShowAsync
> 2015-09-14 18:36:04,532 FINE com.wilutions.itol.ItolAddin onQuit onQuit(
> 2015-09-14 18:36:04,544 FINE com.wilutions.itol.ItolAddin onQuit )onQuit
> 2015-09-14 18:36:04,554 INFO com.wilutions.joa.AddinApplication main launch OK
> 2015-09-14 18:36:04,555 INFO com.wilutions.joa.AddinApplication main BackgTask.done()
> 2015-09-14 18:36:04,555 INFO com.wilutions.joa.AddinApplication main DispatchImpl.doneCOM()
> 2015-09-14 18:36:18,341 INFO com.wilutions.joa.AddinApplication main JoaDll.nativeDoneLogger()
> 2015-09-14 18:36:18,341 INFO com.wilutions.joa.AddinApplication main System.exit(0);

Can you help me with installing the plugin ? 
![image](https://cloud.githubusercontent.com/assets/12086476/9854240/7204b144-5b10-11e5-9b45-6676f8d760f7.png)

**Comment by wolfgangimig** [comment]
This error occurs, when "JOA Util Add-in" is not loaded by Outlook. 

Do you find this Add-in at FILE - Options - Add-ins - Active ... Add-ins?
![image](https://cloud.githubusercontent.com/assets/3779094/9861656/f4320568-5b33-11e5-8ead-554f2002472a.png)

Does it help to uninstall and re-install ITOL?

**Comment by ghost** [comment]
Hello, @wolfgangimig . Thank you for fast reply. 
It's my mistake - i installed 64bit version of ITOL on the 32 bit-versiob MS office. Reinstalling solve the problem. 
Next, i did the cirtificate import from our redmine server, SSL-problem solved also. 
In this moment i have an issue with 401 - HTTP.
In our redmine server turn on "need authentication". it turns out, I can't use the plugin?
Our redmine has a real IP and real domain and we don't want that everyone can see it. 

> 2015-09-16 11:24:55,718 SEVE com.wilutions.itol.Globals lambda$0 Cannot initialize issue service
> file:/C:/Users/filinkovia/AppData/Local/Issue%20Tracker%20for%20Microsoft%20Outlook%2032bit/app/IssueServiceImpl.js:243:3 java.io.IOException: HTTP Status 401, Server returned HTTP response code: 401 for URL: https://redmine.****/projects.json?include=trackers,issue_categories,enabled_modules&offset=0&limit=100
>     at jdk.nashorn.internal.runtime.ECMAException.create(ECMAException.java:113)
>     at jdk.nashorn.internal.scripts.Script$Recompilation$26$7092AAAAA$IssueServiceImpl.send(file:/C:/Users/filinkovia/AppData/Local/Issue%20Tracker%20for%20Microsoft%20Outlook%2032bit/app/IssueServiceImpl.js:243)
>     at jdk.nashorn.internal.scripts.Script$Recompilation$25$9727A$IssueServiceImpl.get(file:/C:/Users/filinkovia/AppData/Local/Issue%20Tracker%20for%20Microsoft%20Outlook%2032bit/app/IssueServiceImpl.js:313)
>     at jdk.nashorn.internal.scripts.Script$Recompilation$29$11439A$IssueServiceImpl.readProjects(file:/C:/Users/filinkovia/AppData/Local/Issue%20Tracker%20for%20Microsoft%20Outlook%2032bit/app/IssueServiceImpl.js:409)
>     at jdk.nashorn.internal.scripts.Script$Recompilation$4$19545$IssueServiceImpl.initialize(file:/C:/Users/filinkovia/AppData/Local/Issue%20Tracker%20for%20Microsoft%20Outlook%2032bit/app/IssueServiceImpl.js:671)
>     at com.wilutions.itol.db.IssueService$$NashornJavaAdapter.initialize(Unknown Source)
>     at com.wilutions.itol.Globals.lambda$0(Globals.java:97)
>     at com.wilutions.itol.Globals$$Lambda$1/309504.run(Unknown Source)
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>     at java.lang.Thread.run(Thread.java:745)
>     at com.wilutions.com.BackgTask$1$1.run(BackgTask.java:80)
> Caused by: java.io.IOException: HTTP Status 401, Server returned HTTP response code: 401 for URL: https://redmine.***/projects.json?include=trackers,issue_categories,enabled_modules&offset=0&limit=100

**Comment by wolfgangimig** [comment]
A similar problem was posted in https://github.com/wolfgangimig/itol/issues/19.

Please check:
- REST API enabled
- Correct API key

**Comment by ghost** [comment]
omg!
it works! 
REST API was enabled.. and API key has been written, but now in "my account" page i saw else key O_o... aaand... then, i write the key in the right filend and it worked. 

Thank you sooo much for your help and sorry for took your time. Your plugin is great!
