### ISSUE TITLE
request: button to perform addition to history instead of modifying the original issue description

### ISSUE THREAD

**Issue by mbrownnycnyc** [wolfgangimig/itol#30]
Thank you for having this be available free and open source!

It would be valuable to offer another button on the issue pane that would not update the original item, but would add an additional history item... for instance what occurs when you click Edit on an issue through the web ui.

Thanks!

**Comment by wolfgangimig** [comment]
Thanks for your suggestion.

I think, the feature is already available. You can add a comment to the history by using the "NEW NOTES" tab:

![image](https://cloud.githubusercontent.com/assets/3779094/10319462/b0c7dd38-6c6e-11e5-87e8-944de90c9cfc.png)

![image](https://cloud.githubusercontent.com/assets/3779094/10319488/d032336c-6c6e-11e5-9f94-c3a69e0242fc.png)
