### ISSUE TITLE
Support projects text search in addition to dropdown

### ISSUE THREAD

**Issue by grisharav** [wolfgangimig/itol#31]
Thanks for the great product.
For a redmine with a large number of projects and subprojects, it gets tedious to search for the project you want when there are dozens of projects. I think a combination of typeahead and dropdown (like the https://select2.github.io/ JS library) can be very useful. We actually use https://www.redmine.org/plugins/redmine_improved_searchbox in the web interface.

Thanks again.

**Comment by wolfgangimig** [comment]
Thanks for your suggestion.
ITOL is written with JavaFX and I haven't found a satisfactory auto completion edit box jet. I continue looking for it.

**Comment by wolfgangimig** [comment]
The new version 2.0 provides auto completion fields for project, tracker, priority, status, and assignee.
