### ISSUE TITLE
Installation doesn't seem to work

### ISSUE THREAD

**Issue by mthomasDE** [wolfgangimig/itol#32]
Hello Wolfgang,

I've been trying to install the plug-in for a few days now, but sadly I doesn't seem to work / install properly.
I'm using a Win 7 pro SP 1 and Outlook 14.0.7153.5000 32-Bit.
As far as I can see the installation runs through without errors.
The folder C:\Users\XXX\AppData\Local\Issue Tracker for Microsoft Outlook 32bit is created, but that's it.
I can't see anything new in my Outlook,... nothing.
Am I missing some point the installation or ...?

Thank you for your help.
Best regards

Martin

**Comment by wolfgangimig** [comment]
Hello Martin,

Is the ITOL Addin listed in Outlook's Option dialog in the section "Active ...Addins" ?

![image](https://cloud.githubusercontent.com/assets/3779094/10317492/fd9f8336-6c64-11e5-85ba-4f2d14a44ea7.png)

Regards
Wolfgang

**Comment by mthomasDE** [comment]
Sadly it is not listed there.
![redmineoutlookaddin](https://cloud.githubusercontent.com/assets/14994509/10359831/71404c66-6d9c-11e5-829c-94771af11bbd.png)

Grüße
Martin

**Comment by wolfgangimig** [comment]
Some days ago, I heard that F-Secure alerts a virus in ITOL 1.4. In order to make sure, that F-Secure is wrong, I submitted the ITOL program to f-secure.com and it was accepted as a false positive. Maybe your VA denies execution too.

ITOL 1.4 is compiled with Oracle JDK 8u45. If I compile ITOL with the latest JDK 8u60, f-secure.com does not detect a virus. 

So I published a new version 1.5 now. Please download again and check, whether it works for you.

Gruß
Wolfgang

**Comment by mthomasDE** [comment]
Hi Wolfgang,
thanks for the fast replies.
If i click on the ITOL button in the start menu, the program starts an is listed in the taskmanager, but there is still nothing sign of it in outlook.
Could it be that i'm doing something wrong in the installation process?
1. Take the msi-file and execute.
2. Open Outlook
or
1. Install the msi
2. Start ITOL as Admin
3. Start Outlook

There's got to be a solution for this, would be great if it were in front of the display.

Grüße

Martin

**Comment by wolfgangimig** [comment]
ITOL is designed to be installed under a normal user account, you do not have to install as administrator. It is important that you use the same Windows user for installing ITOL and for using Outlook.

Have you tried to repair the intallation: 
- goto Program section in Control Panel ( Systemsteuerung\Programme\Programme und Features )
- select "Issue Tracker...." 
- select "Repair" from menu bar or context menu.
- restart Outlook

If this does not help, check the following Registry keys:
- HKEY_CURRENT_USER\SOFTWARE\Microsoft\Office\Outlook\Addins\JoaUtilAddin.Class  should exist with some values (FriendlyName, LoadBehavior,...) and a sub-key
- HKEY_CURRENT_USER\SOFTWARE\Microsoft\Office\Outlook\Addins\ItolAddin.Class should exist with values FirendlyName, LoadBehavior...

If they are not available please try the following steps:
- open a command prompt window 
- change directory to ITOL's installation directory: C:\Users\XXX\AppData\Local\Issue Tracker for Microsoft Outlook 32bit
- Execute "Issue Tracker for Microsoft Outlook 32bit.exe" /RegisterServer user
  ![image](https://cloud.githubusercontent.com/assets/3779094/10410112/2304b080-6f38-11e5-8fc7-c8daf2e0341b.png)
- restart Outlook

Regards
Wolfgang
