### ISSUE TITLE
java certificate error when using https URL / https redmine protocol

### ISSUE THREAD

**Issue by jendik** [wolfgangimig/itol#33]
Hi there,

first of all thanks a lot for all the work you have done. This plugin is great.

The only thing that doesn't work for us is SSL/HTTPS version of redmine connection. Even we have got ssl server certificate from trusted CA, we've got java certificate error.

Could you help us with that?
Could you make your plugin even with selfsigned certificates?

Thanks a lot
Take care
J.

**Comment by wolfgangimig** [comment]
Hi jendik,
maybe the JVM that is distributed with ITOL does not have a root certificate from your CA. 

Have you already followed:
https://github.com/wolfgangimig/itol/wiki/How-to-import-HTTPS-certificate
This steps should also help to use a selfsigned certificate.

Regards
Wolfgang

**Comment by jendik** [comment]
Thx a lot, I will try that..

j.
