### ISSUE TITLE
Error: Invalid Redmine URL

### ISSUE THREAD

**Issue by ghost** [wolfgangimig/itol#35]
Dear Wolfgang,

I am running Windows 10 (64bit) and the Outlook 2016 (32bit). The URL I use is not an IP-adress, but something like: http://redmine......de

The 32bit version of ITOL returns a Java IO error: invalid Redmine URL.
The 64bit version of ITOL does not respond at all (I can't save any settings).

Any ideas welcome!

All the best,
Richard

**Comment by wolfgangimig** [comment]
Hello Richard,

If your Outlook is 32bit, you have to use the 32bit setup for ITOL. Please uninstall the 64bit version and re-install the 32bit setup.

A screenshot of the error dialog could be helpful. Furthermore, the log file could contain useful information. Select a log file and log level DEBUG in the connection dialog. 
If you do not want to post the infos here, send them to wilutions@googlemail.com

Kind regards,
Wolfgang

**Comment by ghost** [comment]
Hello Wolfgang,

thanks for your quick reply!

Uninstalled, rebooted, and installed 32bit version again. Unfortunately, no luck. Please see the error-screens attached.

Greetings,
Richard

---

Wir haben umfirmiert!
Aus Core Consulting wird Phaenom

## www.phaenom.euhttp://www.phaenom.eu/

Richard Hagl, M.S.
Geschäftsführer

Tel:     (089) 38 15 67 13
Mobil:  0177 365 89 90
Fax:    (089) 38 15 67 139
hagl@phaenom.eumailto:hagl@phaenom.eu

Phaenom GmbH
im Münchner Technologie Zentrum
Agnes-Pockels-Bogen 1
80992 München
www.phaenom.euhttp://www.phaenom.eu

Amtsgericht München
HRB 177133
Geschäftsführung:
Richard Hagl

## Eliser Wiedemann

Von: Wolfgang Imig [mailto:notifications@github.com]
Gesendet: Montag, 21. Dezember 2015 22:32
An: wolfgangimig/itol itol@noreply.github.com
Cc: Richard Hagl hagl@phaenom.eu
Betreff: Re: [itol] Error: Invalid Redmine URL (#35)

Hello Richard,

If your Outlook is 32bit, you have to use the 32bit setup for ITOL. Please uninstall the 64bit version and re-install the 32bit setup.

A screenshot of the error dialog could be helpful. Furthermore, the log file could contain useful information. Select a log file and log level DEBUG in the connection dialog.
If you do not want to post the infos here, send them to wilutions@googlemail.commailto:wilutions@googlemail.com

Kind regards,
Wolfgang

**Comment by wolfgangimig** [comment]
Hello Richard,

I can reproduce the behavior with Outlook 2016: the configuration dialog does not show any defaults and the comboboxes are empty. 

I try to find out, why it does not run in Outlook 2016.

Kind regards,
Wolfgang

**Comment by wolfgangimig** [comment]
Please have a look at this version(s), which should solve the Problem with Outlook 2016:
http://www.wilutions.com/files/itol/itol-32bit-2.0.msi
bzw,
http://www.wilutions.com/files/itol/itol-64bit-2.0.msi

The configuration is no more placed on the backstage view. Click on the button "issue pane" in the explorer view. The configuration dialog should pop up and request for the connection properties. Other configuration options can be found under the "Extra" button.

**Comment by wolfgangimig** [comment]
The new version 2.0 works with Outlook 2016.

**Comment by ghost** [comment]
Vielen Dank für die Mühen. Die obigen Links laufen ins leere - ich probiere die aktuelle Version (http://www.wilutions.com/joa/itol.html#downloadTable) schnellstmöglich aus...
