### ISSUE TITLE
Can't install it in window 10, Outlook 2013 professional

### ISSUE THREAD

**Issue by jswpro** [wolfgangimig/itol#36]
Thanks in advance for your distributions.

Nothing installed with a second progress poped-up in the installShield when I download  and install it.
(Issue Tracker for Microsoft Outlook 64bit-1.5.msi, Window 10, Office 2013 Professional 64Bit)

**Comment by wolfgangimig** [comment]
"Nothing installed" ... Please check the following topics:
1. Installation directory "c:\Users...\AppData\Local\Issue Tracker for Microsoft Outlook ...\" contains several DLLs and one EXE file. Furthermore sub-dirs "app" and "runtime".
2. Outlook: Menu "File - Options - Add-Ins" lists "Issue Tracker Addin" as "...active...".
3. Double-check that your Outlook is a 64bit application, e.g. see "Task Manager", "Processes". 
4. The "...second process popped-up..." (progress poped-up): default behavior is that a browser window is opened after installation showing "Thank you for installation...". What kind of "second process" did you see?

**Comment by jswpro** [comment]
Thank you a lot. 
No1 is Ok. But On No2, 
It was not on the active program add-in.  See below images.  Thank you for your feedback.
![image](https://cloud.githubusercontent.com/assets/4322974/12441360/6ef9040e-bf89-11e5-8453-a6e5bbd58426.png)

**Comment by wolfgangimig** [comment]
Did you check 3. - Outlook is 64bit? You may want to try the 32bit installer.

**Comment by jswpro** [comment]
Yes. My outlook is 64 bit. And I tried to install 32bit and 64 bit of Issue Checker both. But That didn't work

**Comment by swatoff** [comment]
Thank you, Wolfgang for your project. 
I have the same problem.

**Comment by wolfgangimig** [comment]
Please check, whether the ITOL application is able to run on your Windows:
- open a Windows Explorer window
- navigate to the installation folder:
  ![image](https://cloud.githubusercontent.com/assets/3779094/12594850/675415c4-c478-11e5-970d-0ee0080c4863.png)
- open a command window:
  ![image](https://cloud.githubusercontent.com/assets/3779094/12594868/80564efc-c478-11e5-9cea-3a04b6191dc2.png)
- type "issue" (without quotes) and press the TAB key
- press ENTER
- any errors?
- check Windows Task Manager, Details: is there an "Issue Tracker...exe" running?

**Comment by swatoff** [comment]
I launch this app. No errors. Task Manager does not have this process.

**Comment by popete** [comment]
I had a similar problem on Windows 10 enterprise / Outlook 32.  Deleted Issue Tracker Process and restarted Outlook - then it worked.
