### ISSUE TITLE
Fehlermeldung

### ISSUE THREAD

**Issue by matsbrucke** [wolfgangimig/itol#37]
Moin,

ich habe gerade V1.1 deinstalliert, gebootet, das Projekt im Redmine gelöscht und V1.5 installiert. Danach erhalte ich folgende Fehlermeldung:

![image](https://cloud.githubusercontent.com/assets/10806821/12536154/89338194-c29c-11e5-9308-3788d82ff80a.png)

Was ist falsch?

**Comment by matsbrucke** [comment]
ach so, ich nutze Outlook 2016 in der 32bit Version

**Comment by matsbrucke** [comment]
nach kompletter Deinstallation, Löschen aller Registry-Keys und neuer Installation lautet die Fehlermeldung Java IO Exception:Invalid Redmine URL: die Dropdownboxen sind auch leer

**Comment by wolfgangimig** [comment]
Die aktuelle Version hat ein Problem mit Outlook 2016 oder mit dessen Backstage-View. Bitte versuchen Sie es mit dieser Version:
http://www.wilutions.com/files/itol/itol-32bit-2.0.msi
bzw,
http://www.wilutions.com/files/itol/itol-64bit-2.0.msi

Die Konfiguration finden Sie jetzt statt unter Optionen direkt im Issue-Pane. Wenn noch keine Verbindung besteht, sollte sich der Verbindungsdialog direkt öffenen. 

Bitte teilen Sie mir mit, ob's mit dieser Version klappt.

**Comment by matsbrucke** [comment]
Die Version funktioniert, wobei ich (nach dem Konfigurationsdialog) am Anfang eine Fehlermeldung erhalten habe, die ein geschlossenes Projekt betraf. Nachdem ich das Projekt geschlossen hatte, gab es die Meldung nicht mehr und es funktioniert alles. Vielen Dank.

**Comment by matsbrucke** [comment]
Ich habe das Projekt geöffnet und dann gelöscht ;)

**Comment by wolfgangimig** [comment]
Mit geschlossenen Projekten kann ich nach einigen Tests kein unschlüssiges Verhalten feststellen. Bitte melden Sie sich nochmal, wenn Sie den Fehler reproduzieren können.
