### ISSUE TITLE
Bug ID in mail attachment

### ISSUE THREAD

**Issue by studs1** [wolfgangimig/itol#40]
First of all: itol is a nice addin!

I have selected the following configuration options:
- Attach mail as outlook .msg
- Insert issue into mail subject

Is it possible to add the issue id to the subject of the attached mail (.msg) ?

I have the following usecase:
1) Customer sends a request by email
2) I read the request (Outlook) and I open a redmine issue via addin. And I assign the request to another Person (eg. Bob). Original Message as attachement (works fine!). but with Issue ID in subject
3) Bob analyzes the request an answers the request in redmine. Probably there are different notes attached to the issue. (eg. further persons are involved) 
4) Now Bob (or I ) want to reply to the original customer email. He (or I) klicks on the original .msg and presses .reply. The Issue Id should be in the subject so that I can send the answer bcc to redmine.

Is this possible? Or are there any other ways to fulfill my needs?

**Comment by wolfgangimig** [comment]
Thank you for this suggestion.
One minor drawback is, that the mail attachment has to be uploaded in a second step after the new issue has been created. But I think it is really useful having the correct issue ID already in the subject when one replies to the .MSG file stored in Redmine.
I add this enhancement to the next version.
