### ISSUE TITLE
outlook msg attachment not working

### ISSUE THREAD

**Issue by arturol76** [wolfgangimig/itol#41]
Hello.
I've configured the add-in to automatically add the mail as outlook msg but it doesn't work.

This is what I do:
First of all I open the issue pane...
...then I select the desired mail...
...click on "assign"...
...Indeed, i see that the mail.msg is in the attachments list, as expected...
...then i click on "create"...
...the issue is properly created in redmine but there is no attachment.

I'm using:
outlook 2013 64bit
redmine 3.2.0

**Comment by wolfgangimig** [comment]
I can reproduce this behavior, when I try to create an issue but leave a required field empty in the first try. The second try, with a value for the required field, creates the issue but does not add the attachments.
