### ISSUE TITLE
Can't get ITOL to run in Outlook 2010 32bit

### ISSUE THREAD

**Issue by skramer-uez** [wolfgangimig/itol#43]
Hi Wolfgang,
I've been trying a couple of times to install ITOL 32bit for my Outlook 2010 32bit (on Windows 7 64bit) but it won't work. I reinstalled it a couple of times, repaired it but with no success. The process appears in the task list, the AddIn is loaded in Outlook, there are entries in the registry, but there is no "Issue Pane" button to be seen in the menu. On my colleagues workstations it works without any problems. How can I fix this?

Thanks for your help...
Sebastian

**Comment by wolfgangimig** [comment]
Hi Sebastian,
by setting the following values in the registry, an additional log file is written.

[HKEY_CURRENT_USER\SOFTWARE\WILUTIONS\JOA\JoaCtrl]
"LogFile"="existing-dir\filename"
"LogLevel"="debug"

Send the logfile to wilutions@goolgemail.com

Best regards,
Wolfgang
