### ISSUE TITLE
Issue Id format suggestion

### ISSUE THREAD

**Issue by AndrewGri** [wolfgangimig/itol#44]
In standard redmine settings the "#" symbol is used to determine the issue number. In Issue Pane plugin the following combination is added to track the issue number: “[R-999]”. Is it possible to replace “–“ character with the “ #” combination to allow the standard redmine parser find the issues in email messages?

**Comment by wolfgangimig** [comment]
Open file IssueServiceImpl.js in the installation directory and replace all occurences of

```
    [R-
```

with

```
    [R#
```

Then re-start Outlook.

**Comment by Sledav** [comment]
Замена символа в теме письма
31 марта 2016 г. 21:41 пользователь "Wolfgang Imig" <
notifications@github.com> написал:

**Comment by AndrewGri** [comment]
Thanks a lot!
