### ISSUE TITLE
File - Issue Tracker missing in Outlook 2010 & 2013

### ISSUE THREAD

**Issue by XBMCdoc** [wolfgangimig/itol#58]
Hello,

When I install ITOL using Outlook 2010 & 2013 I do not see "File - Issue Tracker" to configure the connection to the server. I am not able to use it but the add-on display active. 

In Outlook 2016 it works just fine, setting move to Tracking.

Does version 2.0 no longer support Outlook 2010 & 2013?

Regards.

**Comment by wolfgangimig** [comment]
Hi, 
the version 2.0 is no more configured via backstage view of Outlook (File - Issue Tracker). 
Click on the ribbon button "Issue Pane". If there is no valid configuration, it displays a dialog like:
![image](https://cloud.githubusercontent.com/assets/3779094/21533116/967b96fe-cd57-11e6-8f0d-5b124a981916.png)

Regards,
Wolfgang

**Comment by XBMCdoc** [comment]
Thank you for the quick response. I think there is a security item blocking
the add-on my laptop. To test another environment,  I created a VM with Win
7 x64 and Outlook 2010 x64 and it works just fine. Please close this issue.
