### ISSUE TITLE
Issue Pane doesn't work

### ISSUE THREAD

**Issue by moustou** [wolfgangimig/itol#61]
Hi, 

I installed the add-in successfully but when i'm clicking on the button on the nav-bar but nothing work, i'm using Microsoft Outlook 2016.

Thank you

**Comment by wolfgangimig** [comment]
Please add the following registry entries, restart outlook and click on the button:

    [HKEY_CURRENT_USER\SOFTWARE\WILUTIONS\JOA\JoaCtrl]
    "LogFile"="c:\\temp\\joa.log"
    "LogLevel"="debug"


Send the logfile to wilutions@gmail.com.

**Comment by moustou** [comment]
I create the registry, but i didn't found the log file "joa.log".

**Comment by wolfgangimig** [comment]
Make sure that c:\temp exist and you have full access to this directory. You should be able to create a file there.

Furthermore:
- Open Outlook - File - Options - Add-ins
- Select Issue Tracker Addin...
- Below the list of add-ins, you find the installation path, e.g. c:\Users\Wolfgang\AppData\Local\Issue Tracker for Microsoft Outlook 32bit\
- Close Outlook
- Open a command window and navigate to this path
- Type: "Issue Tracker for Microsoft Outlook 32bit.exe" > out.txt
- Return
- Start Outlook
- Press the issue button
- Close Outlook
Send file out.txt from installation directory to wilutions@gmail.com

**Comment by moustou** [comment]
The problem is resolved by changing the version of the Add-in from 64 bits to 32 bits.

thank you so much
